# SPDX-FileCopyrightText: 2019-2021 Vishesh Handa <me@vhanda.in>
#
# SPDX-License-Identifier: Apache-2.0

name: MacOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-11
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
      - name: Install Deps
        run: brew install git-crypt md5sha1sum gnu-sed create-dmg xmlstarlet
      - name: Get Flutter version from pubspec
        run: |
          set -e

          FLUTTER_VERSION_RANGE=$(cat pubspec.yaml | grep 'flutter:' | head -n 1 | awk '{ print $2 }' | tr -d '"')
          FLUTTER_VERSION="${FLUTTER_VERSION_RANGE:2}"
          echo "FLUTTER_VERSION=${FLUTTER_VERSION}" >> $GITHUB_ENV
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Test
        run: ./scripts/test.sh
      # - name: Test Report
      #   uses: dorny/test-reporter@v1
      #   if: success() || failure()
      #   with:
      #     name: Unit Tests ${{ matrix.os }} ${{ matrix.sdk }}
      #     path: test-results.xml
      #     reporter: jest-junit
      - name: Unlock Secrets
        env:
          GITCRYPT_KEY: ${{ secrets.GITCRYPT_KEY }}
        run: ./scripts/decrypt_secrets.sh
      - name: Setup provisioning profile
        run: ./scripts/add_macos_keys.sh
      - name: Setup Env
        run: dart ./scripts/setup_env.dart
      - run: flutter pub get
      - run: ./scripts/build_macos.sh
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: Installer
          path: build/macos/Build/Products/Release/GitJournal.dmg
          if-no-files-found: error
