# SPDX-FileCopyrightText: 2019-2021 Vishesh Handa <me@vhanda.in>
#
# SPDX-License-Identifier: Apache-2.0

name: Triggers

on:
  push:
    branches:
      - master

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to GitJournal.io
        run: 'curl -X POST ''https://api.github.com/repos/GitJournal/gitjournal.io/actions/workflows/main.yml/dispatches'' -u "vHanda:${{secrets.ACCESS_TOKEN_GITHUB}}" -H "Content-Type: application/json" --data ''{"ref": "master"}'''
        env:
          ACCESS_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN_GITHUB }}

  fdroid:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to FDroid Repo
        run: 'curl -X POST ''https://api.github.com/repos/GitJournal/fdroid/actions/workflows/update_repo.yml/dispatches'' -u "vHanda:${{secrets.ACCESS_TOKEN_GITHUB}}" -H "Content-Type: application/json" --data ''{"ref": "master"}'''
        env:
          ACCESS_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN_GITHUB }}

  poeditor:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deps
        run: sudo apt-get update && sudo apt-get install -y git-crypt
      - name: Unlock Secrets
        run: ./scripts/decrypt_secrets.sh
        env:
          GITCRYPT_KEY: ${{ secrets.GITCRYPT_KEY }}
      - name: Update Translations
        run: ./scripts/upload_translation_en.sh
